fix Visual C 2003 build
All MSVCs need to use the MSVC branch in S_ceil_to_power2. Add support for
VC 2003. I'll deal with VC6 which doesn't have these builtins another time.
Code from https://github.com/danaj/Math-Prime-Util/pull/10
Fixes

C:\sources\cperl\win32>dmake test
cl -c -nologo -GF -W3 -I.\include -I. -I.. -DWIN32 -D_CONSOLE -DNO_STRICT -DPERL
DLL -DPERL_CORE                  -O1 -MD -Zi -DNDEBUG -GL  -DPERL_EXTERNAL_GLOB
-DPERL_IS_MINIPERL -Fomini\toke.obj -Fdmini\toke.pdb ..\toke.c
toke.c
c:\sources\cperl\inline.h(1781) : error C2065: 'M_LOG2E' : undeclared identifier

..\toke.c(8622) : warning C4244: '=' : conversion from 'U16' to 'U8', possible l
oss of data
..\toke.c(8752) : warning C4244: '=' : conversion from 'U16' to 'U8', possible l
oss of data
dmake:  Error code 130, while making 'mini\toke.obj'