File::Glob bsd_glob.c dont use "loop" as a goto label
Using loop as a label conflicts with Perl's "struct loop" and "LOOP" types
and Visual C 2003 in C++ mode (but not the default C build) doesn't like
that. The loop label is from 5.27.1 commit 0db967b2e6
"[perl #131211] fixup File::Glob degenerate matching"

bsd_glob.c(995) : error C2226: syntax error : unexpected type 'loop'

(cherry picked from commit 4d169ec9e2a0eb93170198ffad69a892f91dd199)