fix darwin threads: d_thread_safe_nl_langinfo_l=""
in the 'your system does not have nl_langinfo_l()' case
HAS_THREAD_SAFE_NL_LANGINFO_L was left undefined
 config.h:1976:3: error: invalid preprocessing directive
 # HAS_THREAD_SAFE_NL_LANGINFO_L /**/