sv.h 2 ";"s in a row are illegal
With VC 2003 32 bit cperl, this .i code block was created.

struct sv {
    void* sv_any; U32 sv_refcnt; U32 sv_flags;;
    union { char* svu_pv; IV svu_iv; UV svu_uv;  SV* svu_rv; struct regexp* svu_rx; SV** svu_array; HE** svu_hash; GP* svu_gp; PerlIO *svu_fp; } sv_u;
};

It caused the following fatal error

cl -c -nologo -GF -W3 -I.\include -I. -I.. -DWIN32 -D_CONSOLE -DNO_STRICT -DPERL
DLL -DPERL_CORE                  -O1 -MD -Zi -DNDEBUG -GL  -DPERL_EXTERNAL_GLOB
-DPERL_IS_MINIPERL -Fomini\toke.obj -Fdmini\toke.pdb ..\toke.c
toke.c
c:\sources\cperl\sv.h(282) : error C2059: syntax error : ';'
c:\sources\cperl\sv.h(292) : error C2059: syntax error : '}'
c:\sources\cperl\sv.h(295) : error C2059: syntax error : ';'
c:\sources\cperl\sv.h(296) : error C2371: 'sv_u' : redefinition; different basic
 types
        c:\sources\cperl\sv.h(283) : see declaration of 'sv_u'