gcc-4.8 -flto bug with glibc fcntl2.h
fatal compilation error with enhanced lto optimizations
  __open_missing_mode declared with attribute error: open with O_CREAT in
  second argument needs 3 arguments
which is outright silly, because the compiler should see that the open mode
argument can never contain O_CREAT nor O_TMPFILE.
newer gcc updates fixed that.
The root cause was that we linked with -flto but without -O2.

Nevertheless, ensure that we never call open with such mode bits.