fix most C++ -fpermissive errors
detected via -Dcc=g++-6.
see also 147e38468b8279e26a0ca11e4efd8492016f2702 in perl5 upstream, which fixes the remaining
-Wc++11-compat warnings  C++11 requires a space between string literal and macro

change unshare_hek arg to const HEK*. the subsequent call in with const
and the callers type also.
sv.c: In function 'void Perl_sv_clear(SV*)':
embed.h:728:49: error: invalid conversion from 'const HEK* {aka const hek*}' to 'HEK* {aka hek*}' [-fpermissive]
 #define unshare_hek(a)  Perl_unshare_hek(aTHX_ a)
                                                 ^
sv.c:6737:29: note: in expansion of macro 'unshare_hek'
                             unshare_hek(hek);
                             ^~~~~~~~~~~
In file included from perl.h:5795:0,
                 from sv.c:32:
proto.h:6086:20: note:   initializing argument 1 of 'void Perl_unshare_hek(HEK*)'
 PERL_CALLCONV void Perl_unshare_hek(pTHX_ HEK* hek)

change 2nd case of the SvPV_flags_const_nolen macro to be casted to (void).

unroll goto float_ipow:
error: jump to label 'float_ipow' [-fpermissive]
         float_ipow:
         ^~~~~~~~~~
pp.c:1177:18: note:   from here
             goto float_ipow; /* Can't do negative powers this way.  */
                  ^~~~~~~~~~
pp.c:1220:22: note:   crosses initialization of 'unsigned int diff'
         unsigned int diff = 8 * sizeof(UV);
                      ^~~~
pp.c:1219:22: note:   crosses initialization of 'unsigned int highbit'
         unsigned int highbit = 8 * sizeof(UV);

sv.h:1797:6: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
pp_ctl.c:1236 char * tmps      = SvPV_nomg_const(right, len);

pp_ctl.c:3055:13: error: jump to label 'call_pp_sub' [-fpermissive]
             call_pp_sub: